spring:
  datasource:
    url: jdbc:mysql://rm-cn-kc24qag5i0001fno.rwlb.cn-beijing.rds.aliyuncs.com:3306/heart_cabin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia&allowPublicKeyRetrieval=true
    username: heart_cabin_root
    password: 2694642214t@
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.heartcabin.entity